[Update] Complete Your User Profile - Content text updates from Figma, Checkbox Group Status/Focus Style Update
cfpb/sbl-frontend pull request #169
Opened 2024-01-12 06:29 UTC by shindigira

Closes #177 
Closes #190 

Follow-up to [https://github.com/cfpb/sbl-frontend/pull/146](https://github.com/cfpb/sbl-frontend/issues/120)

## Changes

- Style(fix): Error Message Change - 'You must enter your first name to complete your user profile and access the ~~system~~ platform.'
- Style(fix): Accessibility Change - Institution selection well - dotted line goes around the LEI, TIN and RSSD ID fields as well.
- Style(fix): Removed interfering styles
- Style(feat): Implements the new Checkbox (error/success/warning) and Checkbox Focus from DS/DSR
- Feat(fix): 'Clear Form' no longer clears the list of associated financial institutions

## Local Dev Testing
- `yarn up -i design-system-react` to update DSR package with Checkbox status styling

## Potential Follow-Up PRs
- Margin change between the icon and text in Alerts
- Vertically centering in Alerts

## Screenshots
Focus: Red dotted border
<img width="796" alt="Screenshot 2024-01-17 at 12 12 32 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/e11a18a5-7217-469c-812b-f11e55d1730e">
Focus: dotted line around entire label
<img width="803" alt="Screenshot 2024-01-17 at 12 00 36 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/ffb1b946-d34f-499f-b678-c49a3b199a46">

2024-01-19 02:41 UTC, natalia-fitzgerald commented
@shindigira 
When I hover over the links in the form-level alert I'm seeing the cursor instead of the hand. I think it's because it's missing an href. Can we fix? 
<img width="871" alt="Screenshot 2024-01-18 at 9 15 29 PM" src="https://github.com/cfpb/sbl-frontend/assets/77348967/607877db-c6b9-406a-bebc-2a3ec266450e">

2024-01-20 04:07 UTC, natalia-fitzgerald commented
@shindigira 
Can you double check the error content against the Figma file? It looks like there are a number of discrepancies - where the deployed page isn't matching the Figma file. I have not made recent changes to the content so I guess this was missed until now. 

### Inconsistency between Figma content and deployed page content
- Form-level error links
- Field-level error alert - associate financial institution

2024-01-25 21:41 UTC, billhimmelsbach commented
@natalia-fitzgerald @shindigira 

Don't know if you saw it on the channel, but the latest of this branch is on AWS now as of 12:30 PT / 3:30 ET. Thanks! 👍

2024-01-25 23:23 UTC, natalia-fitzgerald requested changes
@shindigira - This is looking great. I have one small adjustment and then it should be good to go. 

- Reduce the space between the bottom of the text introduction and the notification to 45px?

2024-01-26 00:20 UTC, billhimmelsbach requested changes
I think there's a "Clear form" bug that we'll want to fix, where clicking it removes all financial institution choices.


https://github.com/cfpb/sbl-frontend/assets/19983248/ac5998af-93d7-459d-a985-b21699e8fbfb

2024-01-26 01:59 UTC, billhimmelsbach requested changes

2024-01-26 01:59 UTC, billhimmelsbach commented on src/pages/ProfileForm/Step1Form/Step1Form.tsx
> +    console.log('dataCheckedState:', dataCheckedState);
```suggestion

```

2024-01-26 02:33 UTC, billhimmelsbach approved these changes
Looks good! Natalia is going to take a peek at it, then it should be good to go. 👍

2024-01-26 02:44 UTC, natalia-fitzgerald approved these changes
Great work @shindigira!

2024-01-26 03:06 UTC, merged