[Filing app] Phase 2 - Live data
cfpb/sbl-frontend pull request #301
Opened 2024-03-12 19:37 UTC by meissadia

Closes #285 

## Changes

- Pulls associated institutions from API
- Enables creation of a Filing from the UI (via the API)
- Displays current Filing status, as best we can determine, from API data

## How to test this PR

1. Log into the Frontend with a user that has at least one associated institution
2. Should see a status message indicating: `You have not started the Filing process`
3. Click `Start a Filing`
4. Should see a status message: `Upload your lending data`

## Screenshots
- Implemented statuses: `Start a Filing`, `Upload your data`
  <img width="1225" alt="Screenshot 2024-03-12 at 1 35 06 PM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/94419ddd-9c9e-4291-9773-d20cd39c395a">
- Display when there's an error fetching data
  <img width="1167" alt="Screenshot 2024-03-12 at 1 14 06 PM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/b12ac988-2725-48bd-9623-07f19d535281">

2024-03-12 22:30 UTC, billhimmelsbach commented
Heyo! Can I review this @meissadia with the assumption that the other PR will get merged?

2024-03-13 04:43 UTC, meissadia commented
> Heyo! Can I review this @meissadia with the assumption that the other PR will get merged?

@billhimmelsbach Yes, integration is working well, left PR in draft to allow prerequisites to get reviewed/merged.

2024-03-20 23:14 UTC, billhimmelsbach requested changes
Heyo! This is looking great! There's a different endpoint that we want to use though to see if someone has started a filing for a given LEI.

Instead of `Get Submission Latest` (`/v1/filing/institutions/{lei}/filings/{period_name}/submissions/latest`), we'll want to use `Get Filing` (`/v1/filing/institutions/{lei}/filings/{period_name}`).

We'll be using the `Get Submission Latest` endpoint later when we're trying to get the most recent upload/submission attempt of SBLAR files. If you use the `Get Filing` api endpoint, you can look for a `204` instead of a `500`, which will help with error handling.

![Screenshot 2024-03-20 at 3 44 59 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/afdb792e-f49f-4fe6-90d9-f0fad66993cd)

2024-03-21 03:17 UTC, meissadia commented
Implemented a working solution with the `/v1/filing/institutions/{lei}/filings/{period_name}` endpoint but still need to address the other refactorings.

2024-03-22 16:25 UTC, meissadia commented on src/utils/fetchFilingSubmissionLatest.tsx
> +import { request } from 'api/axiosService';
Moved 👍🏾

2024-03-22 16:30 UTC, meissadia commented on src/pages/Filing/FilingApp/InstitutionCard.tsx
> +  if (axios.isAxiosError(error) && error.response?.status === Error500)
Updated to use requested endpoint.  
 
The way our [axiosService](https://github.com/cfpb/sbl-frontend/blob/main/src/api/axiosService.ts#L31-L46) is currently setup, the `request()` function does not allow access to the API requests' status.  We may need to refactor this to be able to make more refined Frontend decisions using those status codes.

2024-03-22 16:52 UTC, meissadia commented
Adjustments complete, ready for re-review.

2024-03-26 01:50 UTC, billhimmelsbach commented
Not sure what's wrong with my setup, but I get this error consistently, at least on the latest for the repos.

![Screenshot 2024-03-25 at 6 48 05 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/1f65ab6b-1d9c-4894-8752-374a22d38e2b)

Seems like the auth token is only good for the first API call?, even when I'm just using bruno. I'll schedule a meeting after stand-up and you can walk me through how it's looking for you?

2024-03-26 16:58 UTC, billhimmelsbach approved these changes
Heyo! Thanks for debugging it with me, I'll push up a PR with a fix after this. For now, this looks great! 🎉

2024-03-26 17:01 UTC, merged