Design Review Update - Complete Your User Profile (No Associations)
cfpb/sbl-frontend pull request #311
Opened 2024-03-15 19:53 UTC by shindigira

closes #156 
closes #308
closes #310 

## Additional Changes (Updated 04/01/2024)
- content(Complete User Profile): period before quote
- style(CPF No Assoc - FormErrorHeader): FormErrorHeader above the `Step1FormHeader`
- content(Step1FormHeader): update subheading content for Complete user profile with email associations and without email associations
- **fix(CPF No Assoc): added additional_details to post request**
- Removed unused files: `Uploader`, `FilingApp` and `Home`
- **style(additionalDetails - textArea): added .a-text-input class (padding) and reduced rows to 4**

## Additional Changes (Updated 03/28/2024)
- chore(LEI): The Zod check for LEI is now changed to -- A-Z and 0-9 (20 characters)
- feat(Complete User Profile): Added a 'Provide Any Additional Details' section
- feat(FormErrorHeader): Added a `keyLogicFunc` prop that uses logic to choose keys (**used for the scroll links**)
- style(FormHeaderWrapper): Removed marginTop prop since it is handled in `FormWrapper`
- **style(FormWrapper): Created a `marginTop` prop that is used if a **CrumbTrail is used** -- to set a smaller top margin**
- style(FormWrapper): Re-added bottom margin of 60px
- style(InputEntry - Email): Utilizes the `DisplayField` component to **display user's email address**.

## Changes
- style(Fieldgroup): Adhere's to the 770px max-width with box-border (includes borders, margins and padding into the max-width)
- style(SectionIntro): Adhere's to the 670px max-width with box-border (includes borders, margins and padding into the max-width), 30px margin-bottom
- ~~style(FooterWrapper): Footer has 60px margin-top, removed margin-bottom from FormWrapper~~
- style(FormButtonGroup): 10px between buttons
- style(AddFinancialButton): 32.3px ---> 30px margin-bottom
- content(Complete User Profile): Updated content to match the Figma, **period before the ending quotation mark**.

## How to Test (Updated 03/28/2024)
- Test **all** pages (Update the Financial Profile, Point of Contact, Create Profile Form, Create Profile Form - No Associations, Summary, Types of Financial Institution) where `FormWrapper` is used and verify if the **proper top margin** is correct
- FormErrorHeader: Ensure clicking on links and scrolling to the field with the error are functioning properly for both the **Create Profile Form - No Associations** and **Update the Financial Profile** forms.

## Screenshot (Updated 03/28/2024)
<img width="217" alt="Screenshot 2024-03-28 at 7 33 08 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/f11d11a5-a1e5-4bbb-8d8a-6770b582beb0">

2024-03-18 16:18 UTC, meissadia submitted a review, later dismissed
Styles look good 👍🏾 
 
I made one small change to update the following content to match the design file where it reads "Once we have associated your user profile".

Before screenshot:
<img width="719" alt="Screenshot 2024-03-18 at 10 12 03 AM" src="https://github.com/cfpb/sbl-frontend/assets/2592907/063d81eb-2746-465a-a3ed-72cf7ceac2e7">

2024-03-25 15:22 UTC, billhimmelsbach reviewed
Hey, don't want to barge into this PR, but I'm just trying to get everything moved into main. This looks good to me, except are you planning @shindigira on including the "Provide any additional details" section, importing it from Meissa's work? It'll be hard for Natalia to do a final approval without it.

2024-03-27 04:16 UTC, billhimmelsbach requested changes
I went over the email-to-case forms with @natalia-fitzgerald today, and in addition to adding the "Provide any additional details" section I [mentioned](https://github.com/cfpb/sbl-frontend/pull/311#pullrequestreview-1958056975) a few days ago, here are a few other minor design changes we discussed @shindigira:

![Screenshot 2024-03-26 at 9 11 12 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/c5c65046-b01d-4e20-a4ee-d856ce000a49)
- too much space above the breadcrumb (take a peek at the figma)

![Screenshot 2024-03-26 at 9 11 08 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/8dbfe611-a5da-4d0b-9bb1-1ad7fea8ff72)
- `There was a problem completing your profile` should be `There was a problem completing your user profile`
- Clicking on `Enter your financial institution's name (1)`, `Enter your financial institution's Legal Entity Identifier (LEI) (1)`, etc doesn't scroll the error field into view

- LEIs are only going to be all caps, so you can drop the `a-z` part in `Must be 20 characters and only contain a-z, A-Z, and 0-9 (no special characters)`

Looking good so far, and excited to finish off these forms. 👍

2024-03-28 22:51 UTC, billhimmelsbach commented
Hi @natalia-fitzgerald! So I told @shindigira to fix everything except the clicking one of these errors and scrolling to the form field, since a solution needs to be worked out between Sigmund and Meissa. 

![Screenshot 2024-03-28 at 3 44 45 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/b245b56f-0fca-4483-8109-cec4318029f7)



@shindigira will ping us when the rest of the design is fixed, but we'll save fixing the scroll logic for a later PR. 👍

2024-03-29 00:22 UTC, billhimmelsbach requested changes

2024-03-29 00:22 UTC, billhimmelsbach commented on src/components/FooterWrapper.tsx
> +      <FooterCfGov />
Heyo, this causes some weirdness @shindigira by pushing up all the content, like here on the unauthenticated landing page:

_Before_
![Screenshot 2024-03-28 at 5 14 04 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/e4039b89-9119-498e-b923-2be21c49ba72)


_After_
![Screenshot 2024-03-28 at 5 14 15 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/c9633089-980c-40d5-b1ff-2ca879ab41c2)

It also increases the spacing at the bottom too much for other pages:
![Screenshot 2024-03-28 at 5 19 29 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/a3cf23db-d825-4fd6-80de-f5b0177e8b0e)

2024-04-02 14:51 UTC, billhimmelsbach commented
The preview site has been updated with the latest from this PR @natalia-fitzgerald, if you wouldn't mind checking the Complete your user profile (no email associations) again?

2024-04-02 18:17 UTC, natalia-fitzgerald approved these changes
@shindigira 
This looks great! Nice work. 

Can you open a separate PR for these additional changes: 
- style the `<html>` so that the color of the background outside the content is gray for all pages (see screenshot at the bottom of the page)
- Text content in the form-level alert box should be 670px wide (see screenshot - text is currently extending the full width of the box)

![Screenshot 2024-04-02 at 12 29 43 PM](https://github.com/cfpb/sbl-frontend/assets/77348967/6a3913de-0238-4dff-9845-403e9c4ec86a)

2024-04-02 18:27 UTC, billhimmelsbach approved these changes

2024-04-02 18:39 UTC, merged