Design Review - style(App): Fixes having the unnecessary whitespace below the FooterCfGov
cfpb/sbl-frontend pull request #369
Opened 2024-04-02 21:39 UTC by shindigira

closes https://github.com/cfpb/sbl-frontend/issues/365

## Changes
- style(App): Fixes having the unnecessary whitespace below the FooterCfGov

## How to test this PR

1. `yarn install` to get the latest DSR update
2. Go to any page where FooterCfGov is used (basically all)
3. Use mobile view and swipe up at the scroll end OR zoom out (CMD + - multiple times)
4. See how the footer's grey part still extends to the bottom

## Screenshots BEFORE the fix
![Screenshot 2024-04-02 at 12 29 43 PM](https://github.com/cfpb/sbl-frontend/assets/13324863/72228a6a-508d-428c-a1ff-a54f1ef81aeb)
![Screenshot 2024-04-02 at 12 31 41 PM](https://github.com/cfpb/sbl-frontend/assets/13324863/56bc509b-b0d4-4fce-a074-c83f6c810122)

## Screenshot - Fix B (View zoomed out) - Maximizing the footer 
<img width="1552" alt="Screenshot 2024-04-02 at 10 15 16 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/c686516a-978d-451f-b6d3-26930ca808ce">

2024-04-03 01:45 UTC, billhimmelsbach requested changes
Heyo! I think putting the background on a div restricted to the size of this div with `h-dvh` has some weird effects on pages that are larger than the viewport:
![Screenshot 2024-04-02 at 6 27 47 PM](https://github.com/cfpb/sbl-frontend/assets/19983248/275e95c4-55ff-426e-955e-7194f9d77fce)

Digging through git, it looks like this `h-dvh` was set to help with making loading screens take up the viewport, but if you put this on a div that was set to `auto`, this approach works. 🎉

2024-04-03 15:41 UTC, natalia-fitzgerald commented
@shindigira 
I prefer Fix B - extending the gray background - Maximizing the footer.

2024-04-05 02:48 UTC, natalia-fitzgerald commented on src/components/FooterCfGovWrapper.tsx
> +  return <FooterCfGov className='flex-1' />;
@shindigira - How can I see it?

2024-04-08 18:54 UTC, billhimmelsbach commented on src/components/FooterCfGovWrapper.tsx
> +  return <FooterCfGov className='flex-1' />;
This is up for your review on the preview site @natalia-fitzgerald 👍

2024-04-08 18:56 UTC, natalia-fitzgerald approved these changes
Thanks for addressing this. Looks good @shindigira!

2024-04-08 20:22 UTC, billhimmelsbach approved these changes
Looks good! 🎉

2024-04-08 20:43 UTC, merged