style(secondary button): focus and hover styling, pipe styling
cfpb/sbl-frontend pull request #641
Opened 2024-06-04 00:27 UTC by shindigira

closes #580 

## Changes
- style(secondary button): updated state and pipe styling
- Upload - missed small text update
- Summary - links open a new window

| Normal | Hover | Focus | Active |
|--|--|--|--|
|<img width="488" alt="Screenshot 2024-06-03 at 5 56 40 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/ae42839a-73a6-4de0-b7cb-a79f60e64bf0">|<img width="479" alt="Screenshot 2024-06-03 at 5 53 36 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/2fedff37-c0e1-4757-846a-131b78459933">|<img width="483" alt="Screenshot 2024-06-03 at 5 53 48 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/a1181026-c99b-4558-b821-dbf77d806263">|<img width="466" alt="Screenshot 2024-06-03 at 6 05 58 PM" src="https://github.com/cfpb/sbl-frontend/assets/13324863/521b388c-1aea-4fad-a524-5a5d54417aff">|

## Reference
- https://github.com/cfpb/design-system-react/issues/357#issue-2316248266

2024-06-04 02:47 UTC, natalia-fitzgerald requested changes
@shindigira 
I took a look at the secondary button implementation. Can you remove the style called "Focus/Hover" and use what you show for "Focus/Hover" and use it for "Focus" instead? Also, can you show me what 2px for the solid line in the Hover and Focus states would look like? This is more consistent with what we do for inputs, and may also provide more visual contrast when a user interacts with the button. The pipe update looks good.

2024-06-04 18:13 UTC, natalia-fitzgerald commented
@shindigira 
Ok, I updated to exclude Hover/Focus and just include Focus. https://github.com/cfpb/sbl-frontend/issues/580#issue-2315367994

2024-06-04 18:17 UTC, natalia-fitzgerald commented
@shindigira 
Default and Active look good. Still need to nail down Hover and Focus.

2024-06-05 20:35 UTC, meissadia commented on tailwind.config.js
> +        darkPacific: '#0050b4',
Easier to see related colors if this was `pacificDark`?

2024-06-05 20:36 UTC, meissadia submitted a review, later dismissed

2024-06-06 17:58 UTC, meissadia approved these changes

2024-06-07 17:29 UTC, merged