Added global Error Boundary the redirects to /500
cfpb/sbl-frontend pull request #820
Opened 2024-07-23 14:44 UTC by ojbravo

Closes #819

2024-08-01 19:22 UTC, ojbravo commented on src/ErrorFallback.tsx
> +        window.location.href = target.getAttribute('href') ?? '/';
@shindigira Great suggestions! Here are my updates:
- Updated ```Error500.tsx``` to accept props for error messages/code and display Error Details.
- Removed hacky jsdom commands from ```ErrorFallback.tsx```  and instead changed ```<Link>``` to ```<a>``` in ```_shared.tsx```  so the "Visit platform homepage" button would actually load the homepage.
- Changed 500 heading to "Something went wrong" per @billhimmelsbach suggestion

Everything appears to be working smoothly!

2024-08-02 20:47 UTC, billhimmelsbach approved these changes
Looks good! Tested with existing and new errors and it works great! 

I added [one ticket](https://github.com/cfpb/sbl-frontend/issues/834) to make existing custom 500 errors use the error boundary instead.

2024-08-02 20:48 UTC, billhimmelsbach requested changes
Oop, have some git shenanigans to fix.

2024-08-02 21:03 UTC, billhimmelsbach approved these changes
Looks good!

2024-08-02 21:05 UTC, merged