content(Upload): updated based on figma content updates after usability testing
cfpb/sbl-frontend pull request #837
Opened 2024-08-05 15:36 UTC by shindigira

closes #836

## Changes
- content(Upload): updated alert and buttons (e.g. 'Continue to next step') based on figma content updates after usability testing

## How To Test
- Will deploy to dev pub -- compare the figma with what is deployed
- Upload - warnings, errors, success csv's to see the updated messages

[logic-errors_small.csv](https://github.com/user-attachments/files/16501790/logic-errors_small.csv)
[logic-warnings_small.csv](https://github.com/user-attachments/files/16501791/logic-warnings_small.csv)
[pass_123456789TESTBANK456_small.csv](https://github.com/user-attachments/files/16501792/pass_123456789TESTBANK456_small.csv)

2024-08-05 20:50 UTC, natalia-fitzgerald requested changes
@shindigira 
Thanks for sharing these changes. I have a few content revisions that I have noted here.

2024-08-05 20:50 UTC, natalia-fitzgerald commented on src/pages/Filing/FilingApp/FileSubmission.data.tsx
> +    'Navigate through the validation results pages to continue to the required next step.',
Change to: 
"Navigate through the validation results pages to continue."

2024-08-05 20:50 UTC, natalia-fitzgerald commented on src/pages/Filing/FilingApp/FileSubmission.data.tsx
> +    'Navigate through the validation results pages to continue to the required next step.',
Change to: 
"Navigate through the validation results pages to continue."

2024-08-05 20:50 UTC, natalia-fitzgerald commented on src/pages/Filing/FilingApp/FileSubmission.data.tsx
> +    'Your file contained no errors but did contain warnings. Navigate through the error validation results pages to continue to the required next step.',
Change to: 
"Your file contains no errors but does contain warnings. Navigate through the error validation results pages to continue."

2024-08-05 20:50 UTC, natalia-fitzgerald commented on src/pages/Filing/FilingApp/FileSubmission.tsx
> +                    <Heading type='3'>Upload Summary</Heading>
Change to: 
"Upload summary"

2024-08-05 20:50 UTC, natalia-fitzgerald commented on src/pages/Filing/FilingApp/FileDetailsValidation.tsx
> +      ? 'Your file contained no errors and warnings have been verified. Navigate through the validation results pages to continue to the required next step.'
Change to: 
"Your file contains no errors and warnings have been verified. Navigate through the validation results pages to continue."

2024-08-07 19:25 UTC, natalia-fitzgerald commented on src/pages/Filing/FilingApp/FileSubmission.data.tsx
> +      message='Your file must be successfully uploaded and validation checks must be performed to continue to the next step.'
@shindigira - There was a change here that I'm not sure was caught. We removed the second "must be" from this message. 

'Your file must be successfully uploaded and validation checks performed to continue to the next step.'

2024-08-07 19:30 UTC, natalia-fitzgerald requested changes
@shindigira 
I noted one item that should be updated if it hasn't yet.

2024-08-08 00:43 UTC, billhimmelsbach approved these changes
Looks good!

2024-08-08 11:47 UTC, merged