[e2e] [Upload] Tests for syntax errors, logic errors and to verify a downloadable report
cfpb/sbl-frontend pull request #938
Opened 2024-09-18 19:34 UTC by shindigira

closes #777 
closes #802
closes #937 
closes #958

## Changes
- Adds e2e test to check the navigation of when a user uploads a csv that produces syntax errors
- Adds e2e test to check the navigation of when a user uploads a csv that produces logic errors
- e2e: Verifies - a user can download a validation report after a syntax error has been upload
- enhancement: Improves TypeScript handing in `playwright.config.ts`
- feat: deletes individual reports in the `e2e/pages/filing-app/uploadFile/downloads` directory after the download report test finishes
- chore: updated `uploadFile.ts` to be DRY
- feat: Integrate `uploadFile.ts` with completeUploadLogicErrors.spec.ts
- feat: Integrate `uploadFile.ts` with completeUploadSyntaxErrors.spec.ts
- feat: Update `unavailableApis.spec.ts`  with `uploadFile.ts` accordingly

## How to Test
- Run `npx playwright test --ui`
- Run the `completeSyntaxErrors.spec.ts` test
- Run the `completeLogicErrors.spec.ts` test
- Run the `unavailableApis.spec.ts` test
- **Verify downloaded reports are being <ins>deleted</ins> from `e2e/pages/filing-app/uploadFile/downloads`**

## Screenshot
<img width="1392" alt="Screenshot 2024-09-20 at 2 15 50 PM" src="https://github.com/user-attachments/assets/2ea68bc9-e780-4934-8bd6-bca8fd9dc4d4">

2024-09-20 19:34 UTC, billhimmelsbach reviewed
Do you think we can [modify/improve Omar's `uploadFile.ts`](https://github.com/cfpb/sbl-frontend/blob/main/e2e/utils/uploadFile.ts) for these upload tests? It would be great to have a centralized place for uploading logic if it makes sense to do so.

2024-10-09 16:39 UTC, meissadia requested changes
Looking good!  A couple opportunities to reduce code duplication.

2024-10-09 16:39 UTC, meissadia commented on e2e/pages/filing-app/uploadFile/completeUploadLogicErrors.spec.ts
> +    });
Can this be refactored into a shared function? The same logic is used in the `completeUploadSyntax...` test.  It wouldn't be horrible to maintain two instances but still better to only have to change things in one place.

```
const downloadReport = async ({ page }) => {
  // Set up listener for the download event
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download report' }).click();
  const download = await downloadPromise;

  // Save downloaded file to the specified location
  const downloadFilePath = path.join(
    downloadPath,
    await download.suggestedFilename(),
  );
  await download.saveAs(downloadFilePath);

  // Wait for the download to complete
  await download.path();

  // Verify the file exists
  expect(fs.existsSync(downloadFilePath)).toBeTruthy();

  // Verify the file is not empty
  const fileSize = fs.statSync(downloadFilePath).size;
  expect(fileSize).toBeGreaterThan(0);

  // eslint-disable-next-line no-console
  console.log(`Downloaded file path: ${downloadFilePath}`);

  return downloadFilePath;
};
```
 
 ```
     await test.step('Verify downloadable report', async () => {
      downloadFilePath = await downloadReport({ page })
    });
```

2024-10-09 16:39 UTC, meissadia commented on e2e/pages/filing-app/uploadFile/completeUploadLogicErrors.spec.ts
> +  }
Can you also explore refactoring this into a shared function?

2024-10-09 18:08 UTC, meissadia commented on .gitignore
> +e2e/pages/filing-app/uploadFile/downloads/*
This seems unused.

2024-10-09 18:08 UTC, meissadia approved these changes
LGTM 👍🏾

2024-10-09 18:52 UTC, merged