[TextInput] Add a default max length based on input type
cfpb/sbl-frontend pull request #988
Opened 2024-10-04 19:10 UTC by tanner-ricks

[Short description explaining the high-level reason for the pull request]

## Changes

-

## How to test this PR

1.

## Screenshots

## Notes

-

2024-10-10 18:16 UTC, meissadia requested changes
Can you please double check your tests? I'm getting consistent failures in the unicode and length tests:
<img width="619" alt="Screenshot 2024-10-10 at 12 16 34 PM" src="https://github.com/user-attachments/assets/70a5caa2-e3bc-45a6-86ad-6966aa299f12">

2024-10-10 22:53 UTC, tanner-ricks commented
> Can you please double check your tests? I'm getting consistent failures in the unicode and length tests: <img alt="Screenshot 2024-10-10 at 12 16 34 PM" width="619" src="https://private-user-images.githubusercontent.com/2592907/375497181-70a5caa2-e3bc-45a6-86ad-6966aa299f12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MDAzNzcsIm5iZiI6MTcyODYwMDA3NywicGF0aCI6Ii8yNTkyOTA3LzM3NTQ5NzE4MS03MGE1Y2FhMi1lM2JjLTQ1YTYtODZhZC02OTY2YWEyOTlmMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMjI0MTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQxMmYwZjc4MGFkODFhNGNiZTc1NDQ1MGE5ODY4YTdkMDk2NTZjNTgyNjlkZGQ5ODA4NjA3OGFjNGZkMDEwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zt9wcq8QgLtH94MG-TNopVLcmALQD8G53Wn7a-7REkI">

Can't reproduce and can't see the nature of the failures with the information given.

2024-10-22 17:42 UTC, billhimmelsbach approved these changes
Looks good! I think with [this PR](https://github.com/cfpb/sbl-frontend/pull/1023) all tests are passing (see screenshot).

I appreciate the expected/unexpectedValues you use here in the tests and making it easy to make those assertions in the future with inputValidator, and making a text input that has the correct max chars based on type. Thanks!

<img width="1392" alt="Screenshot 2024-10-22 at 10 17 42 AM" src="https://github.com/user-attachments/assets/f050f9eb-0376-484f-ad91-0a19c8172071">

2024-10-22 17:42 UTC, billhimmelsbach commented on e2e/pages/shared-lending-platform/UpdateInstitutionProfile.spec.ts
> +      // fill: controlUnicode,
NIT: Old comment to remove?

2024-10-22 17:42 UTC, billhimmelsbach commented on src/utils/constants.ts
> +export const DefaultInputCharLimit = 255;
I appreciate you adding to this list. Might be something to import from [regtech-regex](https://github.com/cfpb/regtech-regex) someday in the future potentially, maybe after #811 is worked on.

2024-10-22 19:10 UTC, merged